// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOOnU9JMrYMfpyyiLx-y6LU6OEeADR7hA',
    appId: '1:408132408974:web:8706dee77423c29e7d1bdf',
    messagingSenderId: '408132408974',
    projectId: 'pdpquiz-8238a',
    authDomain: 'pdpquiz-8238a.firebaseapp.com',
    storageBucket: 'pdpquiz-8238a.appspot.com',
    measurementId: 'G-E75YWVNQQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOSyLpkkeOfjKSooafm1iSQ5q82mFtm44',
    appId: '1:408132408974:android:d8e2ee4f8658f1977d1bdf',
    messagingSenderId: '408132408974',
    projectId: 'pdpquiz-8238a',
    storageBucket: 'pdpquiz-8238a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzGv7ouRS90gUHhGvR3POWytGVOpM_e3U',
    appId: '1:408132408974:ios:601a89729bfe00c27d1bdf',
    messagingSenderId: '408132408974',
    projectId: 'pdpquiz-8238a',
    storageBucket: 'pdpquiz-8238a.appspot.com',
    iosClientId: '408132408974-73btitgln87k6n9amrsbik0e7vj8qa70.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzGv7ouRS90gUHhGvR3POWytGVOpM_e3U',
    appId: '1:408132408974:ios:601a89729bfe00c27d1bdf',
    messagingSenderId: '408132408974',
    projectId: 'pdpquiz-8238a',
    storageBucket: 'pdpquiz-8238a.appspot.com',
    iosClientId: '408132408974-73btitgln87k6n9amrsbik0e7vj8qa70.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
